#!/usr/bin/env just --justfile

# Using Just: https://github.com/casey/just?tab=readme-ov-file#installation

# List all of the available commands.
default:
  just --list

# Run the web server
web:
	pnpm -r i
	pnpm -r run dev

# Run the CI checks
check:
	pnpm -r i

	# Format the JS packages
	biome check

	# Make sure Typescript compiles
	pnpm -r run check

	# Make sure the JS packages are not vulnerable
	pnpm -r exec pnpm audit

	# Beta: Check for unused imports
	pnpm exec knip --no-exit-code

# Automatically fix some issues.
fix:
	# Fix the JS packages
	pnpm -r i

	# Format and lint
	biome check --fix

	# Make sure the JS packages are not vulnerable
	pnpm -r exec pnpm audit --fix

# Run any CI tests
test:
	# Run the JS tests via node.
	pnpm -r test

# Upgrade any tooling
upgrade:
	# Update the NPM dependencies
	pnpm self-update
	pnpm -r update
	pnpm -r outdated

# Build the packages
build:
	pnpm -r i
	pnpm -r run build
