#!/usr/bin/env bash
set -euo pipefail

# Change directory to root folder
cd "$(dirname "$0")/.."

# Install pnpm for anybody that doesn't have it
corepack enable pnpm

# Install any new dependencies
pnpm i

# Run everything
pnpm all
