#!/usr/bin/env bash
set -euo pipefail

# Change directory to root folder
cd "$(dirname "$0")/.."

# Use pnpm to install dependencies
corepack enable

# Install any new dependencies
pnpm install

# Run everything
pnpm run all
