#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Default to a self-signed certificate
# TODO automatically generate if it doesn't exist.
CERT="${CERT:-dev/localhost.crt}"
KEY="${KEY:-dev/localhost.key}"

# Default to a sqlite database in memory
DATABASE="${DATABASE-sqlite::memory:}"

# Run the relay and forward any arguments
RUST_LOG=info cargo run --bin moq-api -- --cert "$CERT" --key "$KEY" "$@"
