#!/usr/bin/env bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Download the Big Buck Bunny video if it doesn't exist
if [ ! -f dev/bbb.fmp4 ]; then
	if [ ! -f dev/bbb.mp4 ]; then
		echo "Downloading ya boye Big Buck Bunny..."
		wget http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 -O dev/bbb.mp4
	fi

	echo "Converting to a (properly) fragmented MP4..."
	ffmpeg -i dev/bbb.mp4 \
		-c copy \
		-f mp4 -movflags cmaf+separate_moof+delay_moov+skip_trailer+frag_every_frame \
		dev/bbb.fmp4
fi

INPUT=dev/bbb.fmp4 NAME=demo/bbb ./dev/pub "$@"
