#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Connect to localhost by default.
HOST="${HOST:-localhost}"
PORT="${PORT:-4443}"
ADDR="${ADDR:-$HOST:$PORT}"
SCHEME="${SCHEME:-https}"

# Combine the host and name into a URL.
URL="${URL:-"$SCHEME://$ADDR"}"

cargo run --bin moq-clock -- "$URL" "$@"
