#!/usr/bin/env bash
set -euo pipefail

# Change directory to root folder
cd "$(dirname "$0")/.."

# Install any new dependencies
pnpm i

# Run everything
# Override the log level to only show warnings otherwise wasm-bindgen will spam the console
pnpm run cluster
