#!/bin/bash
set -euo pipefail

# Change directory to the moq-gst folder
cd "$(dirname "$0")/../moq-gst"

# Use info logging by default
export RUST_LOG="${RUST_LOG:-info}"

# Connect to localhost by default.
HOST="${HOST:-localhost}"
PORT="${PORT:-4443}"
ADDR="${ADDR:-$HOST:$PORT}"
SCHEME="${SCHEME:-https}"

# Use the name "demo/bbb" for the broadcast.
ROOM="${ROOM:-demo}"
NAME="${NAME:-bbb}"

# Combine the host into a URL.
URL="${URL:-"$SCHEME://$ADDR"}"

# Print out the watch URL
echo "Watch URL: https://quic.video/watch/$ROOM/$NAME?server=$ADDR"

# Make sure we build the gstreamer plugin
cargo build

export GST_PLUGIN_PATH="${PWD}/target/debug${GST_PLUGIN_PATH:+:$GST_PLUGIN_PATH}"

# Some useful debugging environment variables
# export GST_DEBUG_DUMP_DOT_DIR="${PWD}/debug"
# export GST_DEBUG=*:5

# Download the Big Buck Bunny video if it doesn't exist
if [ ! -f ../dev/bbb.fmp4 ]; then
	if [ ! -f ../dev/bbb.mp4 ]; then
		echo "Downloading ya boye Big Buck Bunny..."
		wget http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 -O ../dev/bbb.mp4
	fi

	echo "Converting to a (properly) fragmented MP4..."
	ffmpeg -i ../dev/bbb.mp4 \
		-c copy \
		-f mp4 -movflags cmaf+separate_moof+delay_moov+skip_trailer+frag_every_frame \
		../dev/bbb.fmp4
fi

# Run gstreamer and pipe the output to moq-pub
gst-launch-1.0 -v -e multifilesrc location="../dev/bbb.fmp4" loop=true ! qtdemux name=demux \
    demux.video_0 ! h264parse ! queue ! identity sync=true ! isofmp4mux name=mux chunk-duration=1 fragment-duration=1 ! moqsink url="$URL" room="$ROOM" broadcast="$NAME" \
    demux.audio_0 ! aacparse ! queue ! mux.
