#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Default to a source video
INPUT="${INPUT:-dev/source.mp4}"

# Output the fragmented MP4 to disk for testing.
OUTPUT="${OUTPUT:-dev/output.mp4}"

gst-launch-1.0 -e multifilesrc location="${INPUT}" loop=true ! \
    qtdemux name=demux \
    demux.video_0 ! h264parse ! queue ! mp4mux name=mux streamable=true fragment-duration=1 ! filesink location=${OUTPUT} \
    demux.audio_0 ! aacparse ! queue ! mux.
