#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Generate the self-signed certificate if needed
./dev/cert

# Default to a self-signed certificate
# TODO automatically generate if it doesn't exist.
CERT="${CERT:-dev/localhost.crt}"
KEY="${KEY:-dev/localhost.key}"

# Default to listening on localhost:4443
PORT="${PORT:-4443}"
BIND="${BIND:-[::]:$PORT}"

# A list of optional args
ARGS=""

# Connect to the given URL to get announcements
# TODO default to a public instance?
if [ -n "${ANNOUNCE-}" ]; then
	ARGS="$ARGS --announce $ANNOUNCE"
fi

# Provide our node URL when registering origins.
if [ -n "${HOST-}" ]; then
	ARGS="$ARGS --host $HOST"
fi

echo "Publish URL: https://quic.video/publish/?server=localhost:$PORT"

# Run the relay and forward any arguments
cargo run --bin moq-relay -- --bind "$BIND" --tls-cert "$CERT" --tls-key "$KEY" --dev $ARGS "$@"
