#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Default to a self-signed certificate
# TODO automatically generate if it doesn't exist.
CERT="${CERT:-dev/localhost.crt}"
KEY="${KEY:-dev/localhost.key}"

# Default to listening on localhost:4443
HOST="${HOST:-[::]}"
PORT="${PORT:-4443}"
BIND="${BIND:-$HOST:$PORT}"

# Run the relay and forward any arguments
cargo run --bin moq-dir -- --bind "$BIND" --tls-cert "$CERT" --tls-key "$KEY" -- "$@"
