#!/usr/bin/env bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Download the Big Buck Bunny video if it doesn't exist
if [ ! -f dev/tos.fmp4 ]; then
	if [ ! -f dev/tos.mp4 ]; then
		echo "Downloading a vastly inferior demo movie..."
		wget http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4 -O dev/tos.mp4
	fi

	echo "Converting to a (properly) fragmented MP4..."
	ffmpeg -i dev/tos.mp4 \
		-c copy \
		-f mp4 -movflags cmaf+separate_moof+delay_moov+skip_trailer+frag_every_frame \
		dev/tos.fmp4
fi

INPUT=dev/tos.fmp4 NAME=demo/tos ./dev/pub "$@"
