// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublishCommand } from "./publish/command";
import type { WatchCommand } from "./watch/command";

export type Command = { "Watch": WatchCommand } | { "Publish": PublishCommand };
