// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublishCommand } from "./publish/message";
import type { WatchCommand } from "./watch/message";

export type Command = { "Watch": WatchCommand } | { "Publish": PublishCommand };

export type ConnectionStatus = "Disconnected" | "Connecting" | "Connected" | "Live" | "Offline";

export type Event = "Init" | { "Connection": ConnectionStatus };
