// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WatchCommand = { "Connect": string | null } | { "Canvas": OffscreenCanvas | null } | { "Latency": number } | { "Paused": boolean } | { "Visible": boolean };
