// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Command = { "command": "Connect", url: URL, } | { "command": "Disconnect" } | { "command": "Play" } | { "command": "Stop" } | { "command": "Seek", position: number, } | { "command": "Volume", volume: number, } | { "command": "Canvas", canvas: OffscreenCanvas, } | { "command": "Latency", latency: bigint, };
